### ISSUE TITLE
Error: Partial marker impossible

### ISSUE THREAD

**Issue by knifecake** [thoree/exclusion#1]
While testing the new exclusion GUI import functions I came across this error which does not seem to be related to the GUI or the importers.

(To run the example you may need to modify the paths. In particular, the `global.R` file that is imported lives inside the `inst/exclusionPowerGUI/` folder of the latest version of the shiny-gui branch of the magnusdv/forrel repo).

``` r
library(forrel)
#> Loading required package: pedtools
setwd('~/dev/oslo/forrel/inst/exclusionPowerUI')
source('global.R')

claimPedFile = '../../../exclusion/F21/ep2/claim2.ped'
truePedFile = '../../../exclusion/F21/ep2/claim2.ped'

frequencyDbFile = '../../../exclusion/F21/ep2/db-fam.txt'
caseDataFile = '../../../exclusion/F21/ep2/references-fam.txt'

claim = readPed(claimPedFile)
true = readPed(truePedFile)

claim = attachAlleleFrequenciesToPedigree.familias(ped = claim, path = frequencyDbFile)

claim = attachGenotypeToPedigree.familias(claim, caseDataFile)

exclusionPower(claim, true, c('7', 'POI'), markerindex = 2, plot = F)
#> Removed already typed individuals from internal computations: 1, 2, 3, 4, 5
#> Warning: The function `is_Xmarker()` is renamed to `isXmarker()` and will
#> eventually be removed

#> Warning: The function `is_Xmarker()` is renamed to `isXmarker()` and will
#> eventually be removed

#> Warning: The function `is_Xmarker()` is renamed to `isXmarker()` and will
#> eventually be removed

#> Warning: The function `is_Xmarker()` is renamed to `isXmarker()` and will
#> eventually be removed
#> Error: Partial marker is impossible
```

<sup>Created on 2019-08-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The offending marker is `TH01`:

```
      TH01
   1   7/7
   2   6/7
   3 7/9.3
   4 7/9.3
   5   8/8
   6   -/-
   7   -/-
   8   -/-
 POI   -/-
---------- 
Chrom NA: NA (Mb), NA (cM)
Mutation model: No 
Allele frequencies:
          4           5       6        7        8        9      9.3         10         11
 5.9994e-05 0.000639936 0.29561 0.260284 0.080002 0.123408 0.230887 0.00807919 0.00069993
       13.3          99
 5.9994e-05 0.000269973
```

**Comment by magnusdv** [comment]
This is a correct error message. The genotypes are not compatible with the pedigree (unless there has been a mutation). This creates a division by zero in the probabilities; hence an error is warranted.

Thus, until we implement mutation models in the EP computation, these situations must be dealt with directly. For instance by ignoring the marker, and conveying a message about this to the user.

What do you think, @thoree ?

**Comment by thoree** [comment]
I agree with @magnusdv , the error message is appropriate. I also agree that the marker could be
ignored until mutation is introduced. The function
`pedtools::mendelianCheck` detects most Mendelian errors
and perhaps suffices.

**Comment by knifecake** [comment]
Great! I've just pushed a commit to magnusdv/forrel with the first version of an improved interface for the 'Settings' tab. It now allows excluding markers from the calculation so that they do not cause errors because of mutations. I'll try to add an error message using `pedtools::mendelianCheck` as @thoree suggested.
